configfile: "config/config.yml"
workdir: config["workdir"]

include: "rules/common.smk"
include: "rules/preprocess.smk"
if config["aligner"] == "STAR":
    include: "rules/STAR_align.smk"
elif config["aligner"] == "HISAT2":
    include: "rules/HISAT2_align.smk"
include: "rules/signals.smk"
include: "rules/gene_quantification.smk"
include: "rules/multiqc.smk"

onstart:
    print("\n--- Analysis started ---\n")
onsuccess:
    print("\n--- Workflow finished! ---\n")
onerror:
    print("\n--- An error occurred! ---\n")

localrules: multiqc

rule all:
    input:
        expand(["results/processed/{sample}/{sample}_R1.fastq.gz", "results/processed/{sample}/{sample}_R2.fastq.gz"], sample=samples),
        directory("results/index"),
        expand("results/align/{sample}/.continue", sample=samples),
        expand("results/signals/{sample}/.continue", sample=samples),
        directory("results/rsem_index"),
        expand("results/rsem_quant/{sample}/.continue", sample=samples),
        "results/multiqc/multiqc_report.html"