configfile: "config/config.yml"
workdir: config["workdir"]

include: "rules/common.smk"
include: "rules/align.smk"
include: "rules/signals.smk"
include: "rules/gene_quantification.smk"

onstart:
    print("\n--- Analysis started ---\n")
onsuccess:
    print("\n--- Workflow finished! ---\n")
onerror:
    print("\n--- An error occurred! ---\n")

rule all:
    input:
        directory("results/genome"),
        expand("results/align/{sample}/.continue", sample=samples),
        expand("results/signals/{sample}/.continue", sample=samples),
        directory("results/rsem_index"),
        expand("results/rsem_quant/{sample}/.continue", sample=samples),
        # expand("results/processed/{sample}_R1.fastq.gz", sample=samples),
        # expand("results/processed/{sample}_R2.fastq.gz", sample=samples),
        # "results/processed/multiqc_report.html",