executor: slurm
jobs: 40

set-resources:
  fastp:
    runtime: 240
    slurm_partition: 4hours
    slurm_extra: "--cpu-freq=High-High:Performance"
    threads: 8
    cpus_per_task: 8
    mem_mb: 32000
  index:
    runtime: 240
    slurm_partition: 4hours
    slurm_extra: "--cpu-freq=High-High:Performance"
    threads: 44
    cpus_per_task: 44
    mem_mb: 250000
  align:
    slurm_extra: "--cpu-freq=High-High:Performance"
    threads: 44
    cpus_per_task: 44
    mem_gb: 250
    mem_mb: 250000
  bam_to_signals:
    runtime: 30
    slurm_partition: 30mins
    slurm_extra: "--cpu-freq=High-High:Performance"
    threads: 44
    cpus_per_task: 22
    mem_mb: 250000
  rsem_index:
    runtime: 240
    slurm_partition: 4hours
    slurm_extra: "--cpu-freq=High-High:Performance"
    threads: 44
    cpus_per_task: 44
    mem_mb: 128000
  rsem_quant:
    runtime: 720
    slurm_partition: 12hours
    slurm_extra: "--cpu-freq=High-High:Performance"
    threads: 44
    cpus_per_task: 44
    mem_mb: 128000

use-apptainer: True
apptainer-prefix: workflow/rules/envs
software-deployment-method: apptainer
apptainer-args: -B /zata,/data

# max-jobs-per-timespan: 1/2s
rerun-incomplete: True
printshellcmds: True
# keep-incomplete: True