workdir: "/zata/zippy/ramirezc/rna-smk"
aligner: "STAR"

sequencing:
  endedness: "paired"  # Required: Enum("paired", "single")
  is_stranded: True  # Required: T/F
  strand_direction: "reverse"  # Required: Enum("forward", "reverse", "unstranded")
  rsem_seed: 42
  
input_files:
  metadata: "jobs/2026-01-06/metadata.tsv"
  gtf_file: "jobs/2026-01-06/gencode.v49.basic.annotation.gtf" # Optional: Assert not GZIPPED
  reference_fasta: "jobs/2026-01-06/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta" # Optional: Assert not GZIPPED
  multiqc_config: "jobs/2026-01-06/multiqc_config.yaml"

container: docker://clarity001/rna-smk:latest
